### ISSUE TITLE
Passing a single argument to commandLineOptions

### ISSUE THREAD

**Issue by kazunorisasaki** [payara/ecosystem-gradle#15]
I'd like to pass a single argument to commandLineOptions like below.

build.gradle

```
payaraMicro {
    commandLineOptions = [noCluster: null]
}
```

It means a next command.

```
java -jar microbundle.jar --nocluster
```

**Comment by jGauravGupta** [comment]
Hi @kazunorisasaki,

Thanks for reporting the issue, I have created the internal ticket `GP-22` to address the issue.
